version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'starterappserver'
    restart: 'always'
    hostname: starterapp.local
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./public_html:/usr/local/apache2/htdocs/